language: python
sudo: false
cache: pip
python:
  - '3.6'
  - '3.7-dev'
fail_fast: true
before_install:
  - pip install pycodestyle
script:
  - pycodestyle .
  - python -c "import yaml; yaml.load(open('config.yaml', 'r'))"
