language: python
cache: pip
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install pycodestyle
script:
  - pycodestyle .
  - python -c "import yaml; yaml.load(open('config.yaml', 'r'))"
