language: python
sudo: false
cache: pip
python:
  - '3.5'
  - '3.6'
fail_fast: true
before_install:
  - pip install pycodestyle
script:
  - pycodestyle .
  - py -c "import yaml; yaml.load(open('config.yaml', 'r'))"
