version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.7.0-stretch-browsers
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y libyaml-dev python3.7-dev
      - run: pip install --user -r requirements.txt
      - run: pip install --user pycodestyle
      - run: python -m pycodestyle .
      - run: python -c "import ruamel.yaml; ruamel.yaml.load(open('config.yaml', 'r'), Loader=ruamel.yaml.Loader)"
  two:
    docker:
      - image: circleci/python:3.6-stretch-browsers
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run: pip install --user pycodestyle
      - run: python -m pycodestyle .
      - run: python -c "import ruamel.yaml; ruamel.yaml.load(open('config.yaml', 'r'), Loader=ruamel.yaml.Loader)"

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
