version: 2
jobs:
  one:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: python -V
      - run: sudo pip install Cython
      - run: sudo pip install -r requirements.txt
      - run: sudo pip install pycodestyle
      - run: pycodestyle .
      - run: python -c "import ruamel.yaml; ruamel.yaml.load(open('config.yaml', 'r'), Loader=ruamel.yaml.Loader)"
  two:
    docker:
      - image: circleci/python:3.6-stretch-browsers
    steps:
      - checkout
      - run: python -V
      - run: sudo pip install -r requirements.txt
      - run: sudo pip install pycodestyle
      - run: pycodestyle .
      - run: python -c "import ruamel.yaml; ruamel.yaml.load(open('config.yaml', 'r'), Loader=ruamel.yaml.Loader)"

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
