version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-stretch-browsers
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install pycodestyle
      - run: pycodestyle .
      - run: python -c "import ruamel.yaml; ruamel.yaml.load(open('config.yaml', 'r'), Loader=ruamel.yaml.Loader)"
  build:
    docker:
      - image: circleci/python:3.6-stretch-browsers
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install pycodestyle
      - run: pycodestyle .
      - run: python -c "import ruamel.yaml; ruamel.yaml.load(open('config.yaml', 'r'), Loader=ruamel.yaml.Loader)"
